# Generated by Django 6.0.7 on 2026-10-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('loan_due_week', 'Loan Due - 1 Week'), ('loan_due_3_days', 'Loan Due - 3 Days'), ('loan_due_same_day', 'Loan Due - Same Day'), ('loan_overdue', 'Loan Overdue'), ('reservation_ready', 'Reservation Ready for Pickup')], max_length=20),
        ),
    ]
