# Generated by Django 6.0.7 on 2026-08-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/images/')),
                ('total_copies', models.PositiveIntegerField(default=1)),
                ('available_copies', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado (pendiente de recoger)'), ('prestado', 'Prestado (fuera de la biblioteca)'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='reservado', max_length=10)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_recogida', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='accounts.user')),
            ],
        ),
    ]
