# Generated by Django 6.0.7 on 2026-08-28 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
