# Generated by Django 6.0.7 on 2026-08-28 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_password'),
        ('catalog', '0003_delete_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado (pendiente de recoger)'), ('prestado', 'Prestado (fuera de la biblioteca)'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='reservado', max_length=10)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_recogida', models.DateTimeField(blank=True, null=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='catalog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='accounts.user')),
            ],
        ),
    ]
