# Generated by Django 6.0.7 on 2026-08-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='renovaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
