# Generated by Django 6.0.7 on 2026-09-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_rename_loan_fields_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
